/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        dota: {
          bg: '#060911',
          'bg-light': '#0c1118',
          card: '#0f1720',
          'card-hover': '#141e2b',
          border: '#1a2535',
          'border-light': '#243044',
          accent: '#e74c3c',
          'accent-bright': '#ff4757',
          gold: '#daa520',
          'gold-bright': '#f0c040',
          'gold-dim': '#8b6914',
          radiant: '#92A525',
          'radiant-bright': '#b5cc30',
          dire: '#C23C2A',
          'dire-bright': '#e74c3c',
          str: '#EC3D06',
          agi: '#26E030',
          int: '#00B4F0',
          all: '#ccc',
          mana: '#0078d4',
        },
      },
      fontFamily: {
        display: ['"Cinzel"', 'serif'],
        body: ['"Exo 2"', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'xs': ['0.8125rem', { lineHeight: '1.25rem' }],
        'sm': ['0.9375rem', { lineHeight: '1.375rem' }],
        'base': ['1.0625rem', { lineHeight: '1.625rem' }],
        'lg': ['1.1875rem', { lineHeight: '1.75rem' }],
        'xl': ['1.375rem', { lineHeight: '1.875rem' }],
        '2xl': ['1.625rem', { lineHeight: '2rem' }],
        '3xl': ['2rem', { lineHeight: '2.375rem' }],
        '4xl': ['2.5rem', { lineHeight: '2.75rem' }],
        '5xl': ['3.25rem', { lineHeight: '3.5rem' }],
        '6xl': ['4rem', { lineHeight: '4.25rem' }],
        '7xl': ['5rem', { lineHeight: '5.25rem' }],
        '8xl': ['6.5rem', { lineHeight: '6.5rem' }],
        '9xl': ['8rem', { lineHeight: '8rem' }],
      },
      spacing: {
        '18': '4.5rem',
        '22': '5.5rem',
        '30': '7.5rem',
        '34': '8.5rem',
        '38': '9.5rem',
      },
      borderRadius: {
        '2xl': '1rem',
        '3xl': '1.5rem',
        '4xl': '2rem',
      },
      animation: {
        'glow-pulse': 'glow-pulse 2s ease-in-out infinite',
        'glow-pulse-slow': 'glow-pulse 4s ease-in-out infinite',
        'float': 'float 3s ease-in-out infinite',
        'float-slow': 'float 6s ease-in-out infinite',
        'float-delayed': 'float 4s ease-in-out infinite 1s',
        'slide-up': 'slide-up 0.5s cubic-bezier(0.16,1,0.3,1)',
        'slide-down': 'slide-down 0.3s cubic-bezier(0.16,1,0.3,1)',
        'slide-left': 'slide-left 0.4s cubic-bezier(0.16,1,0.3,1)',
        'slide-right': 'slide-right 0.4s cubic-bezier(0.16,1,0.3,1)',
        'fade-in': 'fade-in 0.3s ease-out',
        'fade-in-up': 'fade-in-up 0.5s cubic-bezier(0.16,1,0.3,1)',
        'scale-in': 'scale-in 0.3s cubic-bezier(0.16,1,0.3,1)',
        'spin-slow': 'spin 8s linear infinite',
        'pulse-soft': 'pulse-soft 2s ease-in-out infinite',
        'shimmer': 'shimmer 2s ease-in-out infinite',
        'border-glow': 'border-glow 3s ease-in-out infinite',
      },
      keyframes: {
        'glow-pulse': {
          '0%, 100%': { boxShadow: '0 0 20px rgba(231,76,60,0.2)' },
          '50%': { boxShadow: '0 0 40px rgba(231,76,60,0.5), 0 0 80px rgba(231,76,60,0.15)' },
        },
        'float': {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-12px)' },
        },
        'slide-up': {
          '0%': { transform: 'translateY(24px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'slide-down': {
          '0%': { transform: 'translateY(-16px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'slide-left': {
          '0%': { transform: 'translateX(24px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        'slide-right': {
          '0%': { transform: 'translateX(-24px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'fade-in-up': {
          '0%': { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'scale-in': {
          '0%': { transform: 'scale(0.9)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        'pulse-soft': {
          '0%, 100%': { opacity: '0.6' },
          '50%': { opacity: '1' },
        },
        'shimmer': {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        'border-glow': {
          '0%, 100%': { borderColor: 'rgba(218,165,32,0.2)' },
          '50%': { borderColor: 'rgba(218,165,32,0.5)' },
        },
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
      boxShadow: {
        'glow-sm': '0 0 10px rgba(218,165,32,0.1)',
        'glow-md': '0 0 20px rgba(218,165,32,0.15)',
        'glow-lg': '0 0 40px rgba(218,165,32,0.2)',
        'glow-red': '0 0 30px rgba(231,76,60,0.2)',
        'glow-blue': '0 0 30px rgba(0,180,240,0.2)',
        'inner-glow': 'inset 0 0 30px rgba(218,165,32,0.05)',
        'epic': '0 25px 50px -12px rgba(0,0,0,0.6), 0 0 30px rgba(218,165,32,0.08)',
      },
    },
  },
  plugins: [],
};
